##
# Allow Thymeleaf templates to be reloaded at dev time.
##
spring:
  profiles:
    active: postgres
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

##
# Tomcat configuration.
##
server:
  port: 8080

##
# Logging configuration.
##
logging:
  level:
    com:
      registration: debug
    org:
      hibernate: debug
